# Site settings
title: Mollie Dawahare and Nick Such's wedding
email: us@nickandmollie.com
description: "Mollie Dawahare and Nick Such are getting married on April 16, 2016 in Pikeville, Kentucky."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.nickandmollie.com" # the base hostname & protocol for your site
permalink: /blog/:year/:month/:day/:title/

# Collections
collections:
 gallery_photos:
  path: /img/gallery/
  output: false

# Build settings
markdown: kramdown